name: deathnote_streamer
description: Death Note Live Streamer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.8.6
  file_picker: ^8.0.3
  http: ^1.1.0
  provider: ^6.1.1
  permission_handler: ^11.3.1
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: DeathNoteFont
      fonts:
        - asset: assets/fonts/deathnote.ttf
