name: deathnote_streamer
description: A Death Note style streaming app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.2
  http: ^1.2.0
  file_picker: ^8.3.0
  video_player: ^2.8.2
  audioplayers: ^5.2.1
  flutter_svg: ^2.0.10
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0
  
  # REPLACED: wakelock -> wakelock_plus to fix version conflict
  wakelock_plus: ^1.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/sounds/
    - assets/animations/

  fonts:
    - family: DeathNote
      fonts:
        - asset: assets/fonts/deathnote.ttf