name: deathnote_streamer
description: A Death Note style streaming app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.5
  http: ^1.2.0
  file_picker: ^8.3.0
  video_player: ^2.8.2
  
  # CHANGED: Use stable version 5.2.1 to avoid the URI error
  audioplayers: ^5.2.1
  
  permission_handler: ^11.3.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: DeathNote
      fonts:
        - asset: assets/fonts/deathnote.ttf